"""database create

Revision ID: 53c75c4ddf90
Revises: dcd9f8c2cf7a
Create Date: 2023-09-13 17:19:53.684590

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '53c75c4ddf90'
down_revision: Union[str, None] = 'dcd9f8c2cf7a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
